/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import model.Cidade;
import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.io.xml.StaxDriver;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.JComboBox;
import model.CidadeBusca;
import model.Cidades;

/**
 *
 * @author User
 */
public class Janela extends javax.swing.JFrame {

    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
        mostrarPrevisao(3040);
    }
    
    Cidades cidadesGlobal;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanellFundo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel0 = new javax.swing.JPanel();
        lblTextTemperatura0 = new javax.swing.JLabel();
        lblMin0 = new javax.swing.JLabel();
        lblMax0 = new javax.swing.JLabel();
        lblIcone0 = new javax.swing.JLabel();
        lblIconeMin0 = new javax.swing.JLabel();
        lblIconeMax0 = new javax.swing.JLabel();
        lblData0 = new javax.swing.JLabel();
        lblTextCondicao0 = new javax.swing.JLabel();
        lblCondicao0 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTextTemperatura1 = new javax.swing.JLabel();
        lblMin1 = new javax.swing.JLabel();
        lblMax1 = new javax.swing.JLabel();
        lblIcone1 = new javax.swing.JLabel();
        lblIconeMin1 = new javax.swing.JLabel();
        lblIconeMax1 = new javax.swing.JLabel();
        lblData1 = new javax.swing.JLabel();
        lblTextCondicao1 = new javax.swing.JLabel();
        lblCondicao1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTextTemperatura2 = new javax.swing.JLabel();
        lblMin2 = new javax.swing.JLabel();
        lblMax2 = new javax.swing.JLabel();
        lblIcone2 = new javax.swing.JLabel();
        lblIconeMin2 = new javax.swing.JLabel();
        lblIconeMax2 = new javax.swing.JLabel();
        lblData2 = new javax.swing.JLabel();
        lblTextCondicao2 = new javax.swing.JLabel();
        lblCondicao2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblTextTemperatura3 = new javax.swing.JLabel();
        lblMin3 = new javax.swing.JLabel();
        lblMax3 = new javax.swing.JLabel();
        lblIcone3 = new javax.swing.JLabel();
        lblIconeMin3 = new javax.swing.JLabel();
        lblIconeMax3 = new javax.swing.JLabel();
        lblData3 = new javax.swing.JLabel();
        lblTextCondicao3 = new javax.swing.JLabel();
        lblCondicao3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblTextTemperatura4 = new javax.swing.JLabel();
        lblMin4 = new javax.swing.JLabel();
        lblMax4 = new javax.swing.JLabel();
        lblIcone4 = new javax.swing.JLabel();
        lblIconeMin4 = new javax.swing.JLabel();
        lblIconeMax4 = new javax.swing.JLabel();
        lblData4 = new javax.swing.JLabel();
        lblTextCondicao4 = new javax.swing.JLabel();
        lblCondicao4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblTextTemperatura5 = new javax.swing.JLabel();
        lblMin5 = new javax.swing.JLabel();
        lblMax5 = new javax.swing.JLabel();
        lblIcone5 = new javax.swing.JLabel();
        lblIconeMin5 = new javax.swing.JLabel();
        lblIconeMax5 = new javax.swing.JLabel();
        lblData5 = new javax.swing.JLabel();
        lblTextCondicao5 = new javax.swing.JLabel();
        lblCondicao5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        comboBoxCidades = new javax.swing.JComboBox<>();
        btnBuscaCidade = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanellFundo.setBackground(new java.awt.Color(204, 204, 204));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTitulo.setText("Tempo em");

        lblTextTemperatura0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTextTemperatura0.setText("TEMPERATURA:");

        lblMin0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMin0.setText("Min");

        lblMax0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMax0.setText("Max");

        lblIcone0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nublado_chuva.png"))); // NOI18N

        lblIconeMin0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/baixo.png"))); // NOI18N

        lblIconeMax0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cima.png"))); // NOI18N

        lblData0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblData0.setText("00/00/0000");

        lblTextCondicao0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTextCondicao0.setText("CONDICÃO: ");

        lblCondicao0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCondicao0.setText("Condicão");

        javax.swing.GroupLayout jPanel0Layout = new javax.swing.GroupLayout(jPanel0);
        jPanel0.setLayout(jPanel0Layout);
        jPanel0Layout.setHorizontalGroup(
            jPanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel0Layout.createSequentialGroup()
                .addGroup(jPanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel0Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblIcone0)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel0Layout.createSequentialGroup()
                                .addComponent(lblTextTemperatura0)
                                .addGap(26, 26, 26)
                                .addComponent(lblIconeMin0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMin0)
                                .addGap(22, 22, 22)
                                .addComponent(lblIconeMax0)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMax0))
                            .addGroup(jPanel0Layout.createSequentialGroup()
                                .addComponent(lblTextCondicao0)
                                .addGap(18, 18, 18)
                                .addComponent(lblCondicao0))))
                    .addGroup(jPanel0Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblData0)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel0Layout.setVerticalGroup(
            jPanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel0Layout.createSequentialGroup()
                .addGroup(jPanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel0Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIcone0))
                    .addGroup(jPanel0Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIconeMin0)
                            .addComponent(lblMin0)
                            .addComponent(lblIconeMax0)
                            .addComponent(lblMax0)
                            .addComponent(lblTextTemperatura0))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTextCondicao0)
                            .addComponent(lblCondicao0))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblData0)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTextTemperatura1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTextTemperatura1.setText("TEMPERATURA:");

        lblMin1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMin1.setText("Min");

        lblMax1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMax1.setText("Max");

        lblIcone1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nublado_chuva.png"))); // NOI18N

        lblIconeMin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/baixo.png"))); // NOI18N

        lblIconeMax1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cima.png"))); // NOI18N

        lblData1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblData1.setText("00/00/0000");

        lblTextCondicao1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTextCondicao1.setText("CONDICÃO: ");

        lblCondicao1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCondicao1.setText("Condicão");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblIcone1)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTextTemperatura1)
                                .addGap(26, 26, 26)
                                .addComponent(lblIconeMin1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMin1)
                                .addGap(22, 22, 22)
                                .addComponent(lblIconeMax1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMax1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTextCondicao1)
                                .addGap(18, 18, 18)
                                .addComponent(lblCondicao1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblData1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIcone1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIconeMin1)
                            .addComponent(lblMin1)
                            .addComponent(lblIconeMax1)
                            .addComponent(lblMax1)
                            .addComponent(lblTextTemperatura1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTextCondicao1)
                            .addComponent(lblCondicao1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblData1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTextTemperatura2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTextTemperatura2.setText("TEMPERATURA:");

        lblMin2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMin2.setText("Min");

        lblMax2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMax2.setText("Max");

        lblIcone2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nublado_chuva.png"))); // NOI18N

        lblIconeMin2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/baixo.png"))); // NOI18N

        lblIconeMax2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cima.png"))); // NOI18N

        lblData2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblData2.setText("00/00/0000");

        lblTextCondicao2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTextCondicao2.setText("CONDICÃO: ");

        lblCondicao2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCondicao2.setText("Condicão");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblIcone2)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTextTemperatura2)
                                .addGap(26, 26, 26)
                                .addComponent(lblIconeMin2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMin2)
                                .addGap(22, 22, 22)
                                .addComponent(lblIconeMax2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMax2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblTextCondicao2)
                                .addGap(18, 18, 18)
                                .addComponent(lblCondicao2))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblData2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIcone2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIconeMin2)
                            .addComponent(lblMin2)
                            .addComponent(lblIconeMax2)
                            .addComponent(lblMax2)
                            .addComponent(lblTextTemperatura2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTextCondicao2)
                            .addComponent(lblCondicao2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblData2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTextTemperatura3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTextTemperatura3.setText("TEMPERATURA:");

        lblMin3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMin3.setText("Min");

        lblMax3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMax3.setText("Max");

        lblIcone3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nublado_chuva.png"))); // NOI18N

        lblIconeMin3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/baixo.png"))); // NOI18N

        lblIconeMax3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cima.png"))); // NOI18N

        lblData3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblData3.setText("00/00/0000");

        lblTextCondicao3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTextCondicao3.setText("CONDICÃO: ");

        lblCondicao3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCondicao3.setText("Condicão");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblIcone3)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblTextTemperatura3)
                                .addGap(26, 26, 26)
                                .addComponent(lblIconeMin3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMin3)
                                .addGap(22, 22, 22)
                                .addComponent(lblIconeMax3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMax3))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblTextCondicao3)
                                .addGap(18, 18, 18)
                                .addComponent(lblCondicao3))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblData3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIcone3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIconeMin3)
                            .addComponent(lblMin3)
                            .addComponent(lblIconeMax3)
                            .addComponent(lblMax3)
                            .addComponent(lblTextTemperatura3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTextCondicao3)
                            .addComponent(lblCondicao3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblData3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTextTemperatura4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTextTemperatura4.setText("TEMPERATURA:");

        lblMin4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMin4.setText("Min");

        lblMax4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMax4.setText("Max");

        lblIcone4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nublado_chuva.png"))); // NOI18N

        lblIconeMin4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/baixo.png"))); // NOI18N

        lblIconeMax4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cima.png"))); // NOI18N

        lblData4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblData4.setText("00/00/0000");

        lblTextCondicao4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTextCondicao4.setText("CONDICÃO: ");

        lblCondicao4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCondicao4.setText("Condicão");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblIcone4)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblTextTemperatura4)
                                .addGap(26, 26, 26)
                                .addComponent(lblIconeMin4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMin4)
                                .addGap(22, 22, 22)
                                .addComponent(lblIconeMax4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMax4))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblTextCondicao4)
                                .addGap(18, 18, 18)
                                .addComponent(lblCondicao4))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblData4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIcone4))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIconeMin4)
                            .addComponent(lblMin4)
                            .addComponent(lblIconeMax4)
                            .addComponent(lblMax4)
                            .addComponent(lblTextTemperatura4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTextCondicao4)
                            .addComponent(lblCondicao4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblData4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTextTemperatura5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTextTemperatura5.setText("TEMPERATURA:");

        lblMin5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMin5.setText("Min");

        lblMax5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMax5.setText("Max");

        lblIcone5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/nublado_chuva.png"))); // NOI18N

        lblIconeMin5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/baixo.png"))); // NOI18N

        lblIconeMax5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cima.png"))); // NOI18N

        lblData5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblData5.setText("00/00/0000");

        lblTextCondicao5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTextCondicao5.setText("CONDICÃO: ");

        lblCondicao5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCondicao5.setText("Condicão");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblIcone5)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblTextTemperatura5)
                                .addGap(26, 26, 26)
                                .addComponent(lblIconeMin5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMin5)
                                .addGap(22, 22, 22)
                                .addComponent(lblIconeMax5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMax5))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(lblTextCondicao5)
                                .addGap(18, 18, 18)
                                .addComponent(lblCondicao5))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblData5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIcone5))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIconeMin5)
                            .addComponent(lblMin5)
                            .addComponent(lblIconeMax5)
                            .addComponent(lblMax5)
                            .addComponent(lblTextTemperatura5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTextCondicao5)
                            .addComponent(lblCondicao5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblData5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Busque por uma cidade:");

        txtBusca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        comboBoxCidades.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboBoxCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCidadesActionPerformed(evt);
            }
        });

        btnBuscaCidade.setText("Buscar");
        btnBuscaCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaCidadeActionPerformed(evt);
            }
        });

        jLabel2.setText("Fonte dos dados: CPTEC/INPE");

        jLabel3.setText("Desenvolvido por: Kléber Albino Moreira");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(comboBoxCidades, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscaCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBuscaCidade)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboBoxCidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanellFundoLayout = new javax.swing.GroupLayout(jPanellFundo);
        jPanellFundo.setLayout(jPanellFundoLayout);
        jPanellFundoLayout.setHorizontalGroup(
            jPanellFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanellFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanellFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanellFundoLayout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanellFundoLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanellFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))))
        );
        jPanellFundoLayout.setVerticalGroup(
            jPanellFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanellFundoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanellFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanellFundoLayout.createSequentialGroup()
                        .addComponent(jPanel0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanellFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanellFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscaCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaCidadeActionPerformed
        comboBoxCidades.removeAllItems();
        try {
            Cidades cidades = Buscas.buscaCidade(txtBusca.getText().replaceAll(" ", "%20"));
            cidadesGlobal = cidades;
            for (int i = 0; i < cidades.getCidade().size(); i++) {
                comboBoxCidades.addItem(cidades.getCidade().get(i).getNome() + " - "+cidades.getCidade().get(i).getUf());
            }

        } catch (IOException ex) {
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscaCidadeActionPerformed

    private void comboBoxCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCidadesActionPerformed
        try {
            int index = comboBoxCidades.getSelectedIndex();
            mostrarPrevisao(cidadesGlobal.getCidade().get(index).getId());
        } catch (Exception e) {

        }
    }//GEN-LAST:event_comboBoxCidadesActionPerformed

    private void mostrarPrevisao(int IdCidade) {                                          
        Cidade cidade = Buscas.previsao(IdCidade);
        lblIcone0.setIcon(getIcon(cidade.getPrevisoes(0).getTempo()));
        lblMin0.setText(cidade.getPrevisoes(0).getMinima()+" °C");
        lblMax0.setText(cidade.getPrevisoes(0).getMaxima()+" °C");
        lblCondicao0.setText(getDescription(cidade.getPrevisoes(0).getTempo()));
        lblData0.setText(cidade.getPrevisoes(0).getDia());

        lblIcone1.setIcon(getIcon(cidade.getPrevisoes(1).getTempo()));
        lblMin1.setText(cidade.getPrevisoes(1).getMinima()+" °C");
        lblMax1.setText(cidade.getPrevisoes(1).getMaxima()+" °C");
        lblCondicao1.setText(getDescription(cidade.getPrevisoes(1).getTempo()));
        lblData1.setText(cidade.getPrevisoes(1).getDia());

        lblIcone2.setIcon(getIcon(cidade.getPrevisoes(2).getTempo()));
        lblMin2.setText(cidade.getPrevisoes(2).getMinima()+" °C");
        lblMax2.setText(cidade.getPrevisoes(2).getMaxima()+" °C");
        lblCondicao2.setText(getDescription(cidade.getPrevisoes(2).getTempo()));
        lblData2.setText(cidade.getPrevisoes(2).getDia());

        lblIcone3.setIcon(getIcon(cidade.getPrevisoes(3).getTempo()));
        lblMin3.setText(cidade.getPrevisoes(3).getMinima()+" °C");
        lblMax3.setText(cidade.getPrevisoes(3).getMaxima()+" °C");
        lblCondicao3.setText(getDescription(cidade.getPrevisoes(3).getTempo()));
        lblData3.setText(cidade.getPrevisoes(3).getDia());

        lblIcone4.setIcon(getIcon(cidade.getPrevisoes(4).getTempo()));
        lblMin4.setText(cidade.getPrevisoes(4).getMinima()+" °C");
        lblMax4.setText(cidade.getPrevisoes(4).getMaxima()+" °C");
        lblCondicao4.setText(getDescription(cidade.getPrevisoes(4).getTempo()));
        lblData4.setText(cidade.getPrevisoes(4).getDia());

        lblIcone5.setIcon(getIcon(cidade.getPrevisoes(5).getTempo()));
        lblMin5.setText(cidade.getPrevisoes(5).getMinima()+" °C");
        lblMax5.setText(cidade.getPrevisoes(5).getMaxima()+" °C");
        lblCondicao5.setText(getDescription(cidade.getPrevisoes(5).getTempo()));
        lblData5.setText(cidade.getPrevisoes(5).getDia());
        
        lblTitulo.setText("Previsão do Tempo para " + cidade.getNome()+" - "+cidade.getUf());

    }
    
    public static String getDescription(String code) {
    switch (code) {
      case "ec":
        return "Encoberto com Chuvas Isoladas";
      case "ci":
        return "Chuvas Isoladas";
      case "c":
        return "Chuva";
      case "in":
        return "Instável";
      case "pp":
        return "Poss. de Pancadas de Chuva";
      case "cm":
        return "Chuva pela Manhã";
      case "cn":
        return "Chuva a Noite";
      case "pt":
        return "Pancadas de Chuva a Tarde";
      case "pm":
        return "Pancadas de Chuva pela Manhã";
      case "np":
        return "Nublado e Pancadas de Chuva";
      case "pc":
        return "Pancadas de Chuva";
      case "pn":
        return "Parcialmente Nublado";
      case "cv":
        return "Chuvisco";
      case "ch":
        return "Chuvoso";
      case "t":
        return "Tempestade";
      case "ps":
        return "Predomínio de Sol";
      case "e":
        return "Encoberto";
      case "n":
        return "Nublado";
      case "cl":
        return "Céu Claro";
      case "nv":
        return "Nevoeiro";
      case "g":
        return "Geada";
      case "ne":
        return "Neve";
      case "nd":
        return "Não Definido";
      case "pnt":
        return "Pancadas de Chuva a Noite";
      case "psc":
        return "Possibilidade de Chuva";
      case "pcm":
        return "Possibilidade de Chuva pela Manhã";
      case "pct":
        return "Possibilidade de Chuva a Tarde";
      case "pcn":
        return "Possibilidade de Chuva a Noite";
      case "npt":
        return "Nublado com Pancadas a Tarde";
      case "npn":
        return "Nublado com Pancadas a Noite";
      case "ncn":
        return "Nublado com Poss. de Chuva a Noite";
      case "nct":
        return "Nublado com Poss. de Chuva a Tarde";
      case "ncm":
        return "Nubl. c/ Poss. de Chuva pela Manhã";
      case "npm":
        return "Nublado com Pancadas pela Manhã";
      case "npp":
        return "Nublado com Possibilidade de Chuva";
      case "vn":
        return "Variação de Nebulosidade";
      case "ct":
        return "Chuva a Tarde";
      case "ppn":
        return "Poss. de Panc. de Chuva a Noite";
      case "ppt":
        return "Poss. de Panc. de Chuva a Tarde";
      case "ppm":
        return "Poss. de Panc. de Chuva pela Manhã";
      default:
          return "Sem dados";
    }
  }
    
   
   public ImageIcon getIcon(String code) {
    switch (code) {
      case "ci":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/sol_chuvas_isoladas.png"));
      case "c":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/chuva.png"));
      case "in":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/nublado_chuva_leve.png"));
      case "pp":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/chuva.png"));
      case "cm":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/chuva_manha.png"));
      case "cn":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/chuva_noite.png"));
      case "pt":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/chuva_manha.png"));
      case "pm":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/chuva_manha.png"));
      case "np":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/nublado_chuva.png"));
	  case "pc":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/chuva.png"));
      case "pn":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/parcialmente_nublado.png"));
      case "cv":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/chuvisco.png"));
      case "ch":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/chuvoso.png"));
      case "t":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/tempestade.png"));
      case "ps":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/predominio_de_sol.png"));
      case "e":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/encoberto.png"));
      case "n":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/nublado.png"));
      case "cl":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/ceu_claro.png"));
      case "nv":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/nevoeiro.png"));
	  case "g":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/geada.png"));
      case "ne":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/neve.png"));
      case "nd":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/nao_definido.png"));
      case "pnt":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/chuva_noite.png"));
      case "psc":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/chuva.png"));
      case "pcm":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/chuva_manha.png"));
      case "pct":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/chuva_manha.png"));
      case "pcn":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/chuva_noite.png"));
      case "npt":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/nublado_chuva.png"));
      case "npn":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/chuva_noite.png"));
      case "ncn":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/chuva_noite.png"));
      case "nct":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/chuva_manha.png"));
      case "ncm":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/chuva_manha.png"));
      case "npm":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/chuva_manha.png"));
      case "npp":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/nublado.png"));
      case "vn":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/nevoeiro.png"));
      case "ct":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/chuva_manha.png"));
      case "ppn":
        return new javax.swing.ImageIcon(getClass().getResource("/imagens/chuva_manha.png"));
      default:
          return new javax.swing.ImageIcon(getClass().getResource("/imagens/nao_definido.png"));
	
    }
  }

     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscaCidade;
    private javax.swing.JComboBox<String> comboBoxCidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel0;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanellFundo;
    private javax.swing.JLabel lblCondicao0;
    private javax.swing.JLabel lblCondicao1;
    private javax.swing.JLabel lblCondicao2;
    private javax.swing.JLabel lblCondicao3;
    private javax.swing.JLabel lblCondicao4;
    private javax.swing.JLabel lblCondicao5;
    private javax.swing.JLabel lblData0;
    private javax.swing.JLabel lblData1;
    private javax.swing.JLabel lblData2;
    private javax.swing.JLabel lblData3;
    private javax.swing.JLabel lblData4;
    private javax.swing.JLabel lblData5;
    private javax.swing.JLabel lblIcone0;
    private javax.swing.JLabel lblIcone1;
    private javax.swing.JLabel lblIcone2;
    private javax.swing.JLabel lblIcone3;
    private javax.swing.JLabel lblIcone4;
    private javax.swing.JLabel lblIcone5;
    private javax.swing.JLabel lblIconeMax0;
    private javax.swing.JLabel lblIconeMax1;
    private javax.swing.JLabel lblIconeMax2;
    private javax.swing.JLabel lblIconeMax3;
    private javax.swing.JLabel lblIconeMax4;
    private javax.swing.JLabel lblIconeMax5;
    private javax.swing.JLabel lblIconeMin0;
    private javax.swing.JLabel lblIconeMin1;
    private javax.swing.JLabel lblIconeMin2;
    private javax.swing.JLabel lblIconeMin3;
    private javax.swing.JLabel lblIconeMin4;
    private javax.swing.JLabel lblIconeMin5;
    private javax.swing.JLabel lblMax0;
    private javax.swing.JLabel lblMax1;
    private javax.swing.JLabel lblMax2;
    private javax.swing.JLabel lblMax3;
    private javax.swing.JLabel lblMax4;
    private javax.swing.JLabel lblMax5;
    private javax.swing.JLabel lblMin0;
    private javax.swing.JLabel lblMin1;
    private javax.swing.JLabel lblMin2;
    private javax.swing.JLabel lblMin3;
    private javax.swing.JLabel lblMin4;
    private javax.swing.JLabel lblMin5;
    private javax.swing.JLabel lblTextCondicao0;
    private javax.swing.JLabel lblTextCondicao1;
    private javax.swing.JLabel lblTextCondicao2;
    private javax.swing.JLabel lblTextCondicao3;
    private javax.swing.JLabel lblTextCondicao4;
    private javax.swing.JLabel lblTextCondicao5;
    private javax.swing.JLabel lblTextTemperatura0;
    private javax.swing.JLabel lblTextTemperatura1;
    private javax.swing.JLabel lblTextTemperatura2;
    private javax.swing.JLabel lblTextTemperatura3;
    private javax.swing.JLabel lblTextTemperatura4;
    private javax.swing.JLabel lblTextTemperatura5;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables
}
